apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-prometheus
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
    vkpr: "true"
plugin: prometheus
